---
blank_issues_enabled: false
contact_links:
  - name: Community Discussions Support
    url: https://github.com/Yuzhii0718/bl-mt798x-dhcpd/discussions
    about: Please ask and answer questions here.